# Fabric Properties - https://fabricmc.net/develop/
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14

# Mod Properties
mod_version=1.0.0
maven_group=com.chatcontrol
archives_base_name=chatcontrol

# Fabric API
fabric_version=0.116.17+1.21.1

# Java
org.gradle.jvmargs=-Xmx1G
